### ISSUE TITLE
Return a better response when LEI association is successful

### ISSUE THREAD

**Issue by jcadam14** [cfpb/regtech-user-fi-management#154]
Right now the response to `curl localhost:8881/v1/admin/me/institutions/ -X PUT  -H "Authorization: Bearer ${RT_ACCESS_TOKEN}"  -H 'Content-Type: application/json' -d '["123456789TESTBANK123"]' | jq -r '.'` just returns 'null' if successful.  Return something more meaningful.

**Comment by guffee23** [comment]
Adding LEI validation from regtech-regex to association endpoint. 
The endpoint currently accepts whatever string is passed in and creates an LEI in KC whether valid or not. 
Also updating the response for update institution endpoint.

**Comment by guffee23** [comment]
Separating the LEI validation out into different issue.
Created [#52](https://github.com/cfpb/regtech-api-commons/issues/52) for this.
