### ISSUE TITLE
Update institution status from boolean to lei status code

### ISSUE THREAD

**Issue by lchen-2101** [cfpb/regtech-user-fi-management#250]
Update institution database remove is_active, and add all statuses shown below to lookup table. Add relational object to institution dao and dto referencing lei_status.

In alembic script, set the current is_active institutions to `ISSUED`, others to `LAPSED`

update* 11/07/24 - only statuses we care about are `ISSUED`, `RETIRED`, and `LAPSED`

**Comment by hkeeler** [comment]
This should probably be a lookup table, like `lei_status` with the various values we should expect here. @nongarak posted the following earlier. I image it would be some subset of those values. We _could_ use Postgres's [`ENUM`](https://www.postgresql.org/docs/current/datatype-enum.html) type too, though then you lose the opportunity to hang extra metadata about each of those values in said lookup table.

For instance, we may want something like...

code | name | can_file
---|---|---
ISSUED | Issued | True
PUBLISHED | Published | False
DUPLICATE | Duplicate | False
LAPSED | Lapsed | False
...

---

![image](https://github.com/user-attachments/assets/75a79d0b-645a-4f6a-afa7-85833c975f90)

**Comment by nongarak** [comment]
This is the list of all possible values, but in reality there are only a few in our FI3 system. We can account for all of them if we like, but for now the only ones that appear are: 

<img width="522" alt="image" src="https://github.com/user-attachments/assets/96ca5ea3-7651-4c41-b816-002aa1d239b6">

This is with our incredibly wide swath of all legal LEIs. Reading about the different statuses here, I think it would actually be safe to exclude them entirely from our filters.

RETIRED - results from liquidation, insolvency, dissolution of a legal entity, or a merger/acquisition where the Legal Entity ceases operation as the result of a merger
DUPLICATE - results from an entity registering twice and it being caught by GLEIF - record is frozen and not active. 
ANULLED - results from any other assignment error after an LEI has been publicly issued - record is frozen and not active.

PENDING_TRANSFER and PENDING_ARCHIVAL are used in the transitional period between the receipt of a porting request by a Sending LOU and the final confirmation of the transfer. The Sending LOU changes the record status to PENDING_TRANSFER and the Receiving LOU publishes a new file with the registration status ISSUED. 

"For a short period of time a given record may appear more than once in a published concatenated file. This case occurs at the end of the transfer process, when the Sending LOU publishes their file with RegistrationStatus PENDING_ARCHIVAL and the Receiving LOU publishes their file with the registration status ISSUED. The time window for these transient states is limited by a transfer protocol shared between GLEIF and the LEI issuers (see Use Case 4.19). On average, transfers SHALL be completed within five to ten business days."

I think that means we should retain the PENDING_TRANSFER records, but PENDING_ARCHIVAL can go. In case an FI is being transferred and we need to know that, we can keep the PENDING_TRANSFER until the new record with status ISSUED is originated.

**Comment by nongarak** [comment]
<img width="601" alt="image" src="https://github.com/user-attachments/assets/ba2715de-05ee-4446-bbce-05b95e6128e5">
Page 28 of this doc, if you're interested. 
[2023-03-07_state-transition-validation-rules_v2.7.1_final.pdf](https://github.com/user-attachments/files/17648511/2023-03-07_state-transition-validation-rules_v2.7.1_final.pdf)

**Comment by nongarak** [comment]
Yes, we would actually filter them out of the initial SQL queries of the GLEIF database. You shouldn't need to filter them out on the SBL platform import process.

**Comment by hkeeler** [comment]
So, sounds like the only 3 status the API needs to care about are `ISSUED`, `LAPSED`, and `RETIRED`?

**Comment by nongarak** [comment]
> So, sounds like the only 3 status the API needs to care about are `ISSUED`, `LAPSED`, and `RETIRED`?

I think so. Query if we want to keep the transient statuses (PENDING_*) - they will drop out in 5-10 business days and be replaced by a new LEI record with status ISSUED.

**Comment by jcadam14** [comment]
@nongarak @hkeeler @lchen-2101 @nargis-sultani 
Looking at the current FI3 data file, the states we're ingesting are ANNULLED, DUPLICATE, ISSUED, LAPSED, PENDING_ARCHIVAL, PENDING_TRANSFER, and RETIRED

I wrote an internal fi3-data story to change our current set of is_active to instead set the status, but if we're only concerning ourselves with ISSUED, LAPSED, and RETIRED, how should we process those other states?

**Comment by lchen-2101** [comment]
> @nongarak @hkeeler @lchen-2101 @nargis-sultani Looking at the current FI3 data file, the states we're ingesting are ANNULLED, DUPLICATE, ISSUED, LAPSED, PENDING_ARCHIVAL, PENDING_TRANSFER, and RETIRED
> 
> I wrote an internal fi3-data story to change our current set of is_active to instead set the status, but if we're only concerning ourselves with ISSUED, LAPSED, and RETIRED, how should we process those other states?

need to defer to @nongarak , but I believe they are working on filtering out those on the file generation script; I think we can either just update the import to change from boolean to the status provided, and let those outliers fail; or filter them out on the import. I think I'm ok with them failing the insert / update for now; since they still would let the legitimate records through.

**Comment by jcadam14** [comment]
> > @nongarak @hkeeler @lchen-2101 @nargis-sultani Looking at the current FI3 data file, the states we're ingesting are ANNULLED, DUPLICATE, ISSUED, LAPSED, PENDING_ARCHIVAL, PENDING_TRANSFER, and RETIRED
> > I wrote an internal fi3-data story to change our current set of is_active to instead set the status, but if we're only concerning ourselves with ISSUED, LAPSED, and RETIRED, how should we process those other states?
> 
> need to defer to @nongarak , but I believe they are working on filtering out those on the file generation script; I think we can either just update the import to change from boolean to the status provided, and let those outliers fail; or filter them out on the import. I think I'm ok with them failing the insert / update for now; since they still would let the legitimate records through.

Ok cool.  Been working with @nargis-sultani on updates to this PR and I did write an fi3-data story already to change the ingest for status (once this is released to staging).  Just wasn't sure if we should filter there, or map certain states to one of the three we care about here (ISSUED, RETIRED or LAPSED), or what.

**Comment by nongarak** [comment]
Sorry I'm just tuning into this - we will be filtering out the other states in the actual generation script, to be clear. Working on that today (hopefully)
