### ISSUE TITLE
Remove field length restrictions on FI

### ISSUE THREAD

**Issue by lchen-2101** [cfpb/regtech-user-fi-management#256]
Need to undo https://github.com/cfpb/regtech-user-fi-management/issues/235, as FI3 import has valid entities that exceed those limits.

Will need to update revision `6dd77f09fae6` to do nothing (or try/catch), and have new revision to update the types back to `sa.String`, so environments with the long strings in db won't fail on the old revision, and environments where `6dd77f09fae6` already ran can get the update with new revision.

**Comment by jcadam14** [comment]
Did we want to remove all the restrictions or just the restrictions on the FI name, parent name, etc and keep the restrictions on addresses?
